name: Build and Release PlayCanvasSync

on:
  push:
    branches:
      - main # Trigger only on pushes to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: |
          dotnet build -c Release

      - name: Zip build artifacts
        run: |
          mkdir output
          Compress-Archive -Path ./PlayCanvasGitConnector/bin/Release/* -DestinationPath ./output/PlayCanvasSync.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0-${{ github.run_number }} # Unique tag using workflow run number
          release_name: Release v1.0.0-${{ github.run_number }}
          body: "This is an automated release."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/PlayCanvasSync.zip
          asset_name: PlayCanvasSyncTool.zip
          asset_content_type: application/zip
